config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  resources :questions do
    resources :comments, only: %i[create destroy]
    
    resources :answers, except: %i[new show]
  end

  resources :answers, except: %i[new show] do
    resources :comments, only: %i[create destroy]
  end

  root 'pages#index'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Commentable
  
  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include QuestionsAnswers

  before_action :set_question!
  before_action :set_answer!, except: :create

  def update
    if @answer.update answer_update_params
      flash[:success] = t '.success'
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def edit
    redirect_to root_path unless current_user_check?(@answer)
  end

  def create
    @answer = @question.answers.build answer_create_params

    if @answer.save
      flash[:success] = t '.success'
      redirect_to question_path(@question)
    else
      load_question_answers(do_render: true)
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = t '.success'
    redirect_to question_path(@question)
  end

  private

  def answer_create_params
    params.require(:answer).permit(:body).merge(user: current_user)
  end

  def answer_update_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card' do %>
  <section class="card-header">
      <%= t('answers.writed_by') %> <%= answer.user.name_or_email %>
      <small>(<time datetime="<%= answer.formatted_created_at %>">
        <%= answer.formatted_created_at %>
      </time>)</small>
  </section>

  <div class="card-body">
    <section class="card-text">
      <div class="mt-2 mb-3 fs-4">
        <%= sanitize answer.body %>
      </div>
    </section>
    <% if current_user_check?(answer) %>
    <%= link_to t('global.button.edit'), edit_question_answer_path(question, answer), 
      class: 'btn btn-secondary btn-sm' %>
    <%= link_to t('global.button.delete'), question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
      data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
    <% end %>
  </div>
<% end %>

<%= render 'comments/commentable', commentable: answer, comment: @comment,
  html_id: dom_id(answer, 'comment_form') %>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>
  <% if user_signed_in? %>
    <%= f.submit t('global.button.submit'), class: 'btn btn-success' %>
  <% else %>
    <%= link_to t('answers.please_log_in'), new_session_path, class: 'btn btn-dark' %>
  <% end %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1><%= t '.title'%></h1>

<%= render 'form' %>